### ISSUE TITLE
Crash with Optifine but on Cleanroom loader [0.2.3]

### ISSUE THREAD

**Issue by Margatroidu** [Rongmario/Naughthirium#6]
Crash with Optifine on Cleanroom loader [0.2.3]

[crash-2024-12-06_00.02.09-client.txt](https://github.com/user-attachments/files/18030184/crash-2024-12-06_00.02.09-client.txt)

**Comment by Margatroidu** [comment]
without Cleanroom, everything works fine

**Comment by Rongmario** [comment]
Full log please

**Comment by Margatroidu** [comment]
> Full log please

This is the full log
or do you mean something else?

**Comment by Rongmario** [comment]
latest.log/debug.log

**Comment by Margatroidu** [comment]
Full log:
https://mclo.gs/T8rqCYX

Crash report:
https://mclo.gs/zxDm5ne

**Comment by ghost** [comment]
Happens on Cleanroom 0.2.4-alpha too

**Comment by ZZZank** [comment]
looks surprising similar to [this issue comment](https://github.com/Meldexun/Nothirium/pull/87#issuecomment-1774439254)

**Comment by erialsan** [comment]
Similar issues

**Comment by Rongmario** [comment]
Fixed in latest.
